export interface TeluguWord {
  word: string
  transliteration: string
}

export const twoLetterWords: TeluguWord[] = [
  { word: "అమ్మ", transliteration: "Amma" },
  { word: "ఆవు", transliteration: "Aavu" },
  { word: "ఆమె", transliteration: "Aame" },
  { word: "ఇల్లు", transliteration: "Illu" },
  { word: "ఈగ", transliteration: "Eega" },
  { word: "ఉమ", transliteration: "Uma" },
  { word: "ఊడ", transliteration: "Uuda" },
  { word: "ఋషి", transliteration: "Rushi" },
  { word: "ఎండ", transliteration: "Enda" },
  { word: "ఏడు", transliteration: "Aedu" },
  { word: "ఐదు", transliteration: "Aidu" },
  { word: "ఒక", transliteration: "Oka" },
  { word: "ఓడ", transliteration: "Oda" },
  { word: "ఔటు", transliteration: "Autu" },
  { word: "అంబ", transliteration: "Amba" },
  { word: "కన్ను", transliteration: "Kannu" },
  { word: "కాకి", transliteration: "Kaaki" },
  { word: "కిత", transliteration: "Kita" },
  { word: "కీలు", transliteration: "Keelu" },
  { word: "కుక్క", transliteration: "Kukka" },
  { word: "కూడు", transliteration: "Kuudu" },
  { word: "కుజ", transliteration: "Kuja" },
  { word: "కృషి", transliteration: "Krushi" },
  { word: "కెంపు", transliteration: "Kempu" },
  { word: "కేక", transliteration: "Keka" },
  { word: "కైపు", transliteration: "Kaipu" },
  { word: "కొంగు", transliteration: "Kongu" },
  { word: "కొత్త", transliteration: "Kottha" },
  { word: "కోతి", transliteration: "Kothi" },
  { word: "కౌలు", transliteration: "Kaulu" },
  { word: "కంచు", transliteration: "Kanchu" },
  { word: "ఖర", transliteration: "Khara" },
  { word: "ఖాదీ", transliteration: "Khadi" },
  { word: "గడ్డి", transliteration: "Gaddi" },
  { word: "గాలి", transliteration: "Gaali" },
  { word: "గీత", transliteration: "Geeta" },
  { word: "గింజ", transliteration: "Ginja" },
  { word: "గుడి", transliteration: "Gudi" },
  { word: "గూడు", transliteration: "Guudu" },
  { word: "గృహ", transliteration: "Gruha" },
  { word: "గెల", transliteration: "Gela" },
  { word: "గేదె", transliteration: "Gedhe" },
  { word: "గొడ్డు", transliteration: "Goddu" },
  { word: "గోడు", transliteration: "Godu" },
  { word: "గౌరి", transliteration: "Gauri" },
  { word: "గాను", transliteration: "Gaanu" },
  { word: "గంగ", transliteration: "Ganga" },
  { word: "గంజి", transliteration: "Ganji" },
  { word: "ఘంట", transliteration: "Ghanta" },
  { word: "చలి", transliteration: "Chali" },
  { word: "చారు", transliteration: "Chaaru" },
  { word: "చాట", transliteration: "Chaata" },
  { word: "చిక్కు", transliteration: "Chikku" },
  { word: "చీమ", transliteration: "Cheema" },
  { word: "చుట్టు", transliteration: "Chuttu" },
  { word: "చూపు", transliteration: "Chuupu" },
  { word: "చెట్టు", transliteration: "Chettu" },
  { word: "చేడు", transliteration: "Chedu" },
  { word: "చైను", transliteration: "Chainu" },
  { word: "చొక్కా", transliteration: "Chokka" },
  { word: "చోటు", transliteration: "Chotu" },
  { word: "చౌక", transliteration: "Chauka" },
  { word: "చంక", transliteration: "Chanka" },
  { word: "జడ", transliteration: "Jada" },
  { word: "జాజి", transliteration: "Jaaji" },
  { word: "జింక", transliteration: "Jinka" },
  { word: "జీడి", transliteration: "Jeedi" },
  { word: "జుట్టు", transliteration: "Juttu" },
  { word: "జూలు", transliteration: "Juulu" },
  { word: "జెట్టి", transliteration: "Jetti" },
  { word: "జేజే", transliteration: "Jeje" },
  { word: "జైలు", transliteration: "Jailu" },
  { word: "జోడు", transliteration: "Jodu" },
  { word: "జౌళి", transliteration: "Jauli" },
  { word: "జంకు", transliteration: "Janku" },
  { word: "టపా", transliteration: "Tapa" },
  { word: "టాపు", transliteration: "Taapu" },
  { word: "టింకు", transliteration: "Tinku" },
  { word: "టీకా", transliteration: "Teeka" },
  { word: "టంకె", transliteration: "Tanke" },
  { word: "టేకు", transliteration: "Teku" },
  { word: "టైము", transliteration: "Time-u" },
  { word: "టోపి", transliteration: "Topi" },
  { word: "డబ్బు", transliteration: "Dabbu" },
  { word: "డాలు", transliteration: "Daalu" },
  { word: "డెక్క", transliteration: "Dekka" },
  { word: "డేగ", transliteration: "Dega" },
  { word: "డొక్క", transliteration: "Dokka" },
  { word: "డోలు", transliteration: "Dolu" },
  { word: "ఢక్క", transliteration: "Dhakka" },
  { word: "ఢాక", transliteration: "Dhaka" },
  { word: "ఢిల్లీ", transliteration: "Delhi" },
  { word: "తల", transliteration: "Thala" },
  { word: "తాత", transliteration: "Thata" },
  { word: "తిక్క", transliteration: "Thikka" },
  { word: "తీగ", transliteration: "Theega" },
  { word: "తుది", transliteration: "Thudhi" },
  { word: "తూము", transliteration: "Thuumu" },
  { word: "తెచ్చు", transliteration: "Thecchu" },
  { word: "తేలు", transliteration: "Thelu" },
  { word: "తృష్ణ", transliteration: "Trushna" },
  { word: "తొట్టి", transliteration: "Thotti" },
  { word: "తోలు", transliteration: "Tholu" },
  { word: "తాడు", transliteration: "Taadu" },
  { word: "తంతి", transliteration: "Tanthi" },
  { word: "దయ", transliteration: "Daya" },
  { word: "దడ", transliteration: "Dada" },
  { word: "దారి", transliteration: "Daari" },
  { word: "దిక్కు", transliteration: "Dikku" },
  { word: "దీటు", transliteration: "Deetu" },
  { word: "దుత్త", transliteration: "Duttha" },
  { word: "దూడ", transliteration: "Duuda" },
  { word: "దృష్టి", transliteration: "Drushti" },
  { word: "దెబ్బ", transliteration: "Debba" },
  { word: "దేవి", transliteration: "Devi" },
  { word: "దైవం", transliteration: "Daivam" },
  { word: "దొర", transliteration: "Dora" },
  { word: "దోర", transliteration: "Dora - long 'o'" },
  { word: "దౌడు", transliteration: "Daudu" },
  { word: "దండి", transliteration: "Dandi" },
  { word: "ధర", transliteration: "Dhara" },
  { word: "ధాత", transliteration: "Dhata" },
  { word: "ధూళి", transliteration: "Dhuuli" },
  { word: "నగ", transliteration: "Naga" },
  { word: "నక్క", transliteration: "Nakka" },
  { word: "నారు", transliteration: "Naaru" },
  { word: "నిద్ర", transliteration: "Nidra" },
  { word: "నీరు", transliteration: "Neeru" },
  { word: "నుగ్గు", transliteration: "Nuggu" },
  { word: "నూరు", transliteration: "Nuuru" },
  { word: "నెత్తి", transliteration: "Netthi" },
  { word: "నేత", transliteration: "Neta" },
  { word: "నైసు", transliteration: "Naisu" },
  { word: "నొప్పి", transliteration: "Noppi" },
  { word: "నోరు", transliteration: "Noru" },
  { word: "నౌక", transliteration: "Nauka" },
  { word: "నంది", transliteration: "Nandi" },
  { word: "పగ", transliteration: "Paga" },
  { word: "పాపి", transliteration: "Paapi" },
  { word: "పిడి", transliteration: "Pidi" },
  { word: "పీత", transliteration: "Peetha" },
  { word: "పులి", transliteration: "Puli" },
  { word: "పూవు", transliteration: "Puuvu" },
  { word: "పెండ్లి", transliteration: "Pendli" },
  { word: "పెద్ద", transliteration: "Pedda" },
  { word: "పేద", transliteration: "Peda" },
  { word: "పైరు", transliteration: "Pairu" },
  { word: "పొద", transliteration: "Poda" },
  { word: "పోతు", transliteration: "Pothu" },
  { word: "పాను", transliteration: "Paanu" },
  { word: "ఫౌజు", transliteration: "Fauju" },
  { word: "బడి", transliteration: "Badi" },
  { word: "బాతు", transliteration: "Baatu" },
  { word: "బిడ్డ", transliteration: "Bidda" },
  { word: "బీద", transliteration: "Beeda" },
  { word: "బుర్ర", transliteration: "Burra" },
  { word: "బూజు", transliteration: "Buuju" },
  { word: "బెండ", transliteration: "Benda" },
  { word: "బేలు", transliteration: "Belu" },
  { word: "బైట", transliteration: "Baita" },
  { word: "బొట్టు", transliteration: "Bottu" },
  { word: "బోను", transliteration: "Bonu" },
  { word: "భట్టు", transliteration: "Bhattu" },
  { word: "భార్య", transliteration: "Bharya" },
  { word: "భిక్ష", transliteration: "Bhiksha" },
  { word: "భీతి", transliteration: "Bheethi" },
  { word: "భుక్తి", transliteration: "Bhukthi" },
  { word: "భూమి", transliteration: "Bhuumi" },
  { word: "భృతి", transliteration: "Bhruthi" },
  { word: "భేరి", transliteration: "Bheri" },
  { word: "భోగి", transliteration: "Bhogi" },
  { word: "భౌభౌ", transliteration: "Bhaubhau" },
  { word: "మర్రి", transliteration: "Marri" },
  { word: "మాట", transliteration: "Maata" },
  { word: "మామ", transliteration: "Maama" },
  { word: "మిద్దె", transliteration: "Midde" },
  { word: "మీద", transliteration: "Meeda" },
  { word: "ముక్కు", transliteration: "Mukku" },
  { word: "మూతి", transliteration: "Muuthi" },
  { word: "మృతి", transliteration: "Mruthi" },
  { word: "మెడ", transliteration: "Meda" },
  { word: "మేక", transliteration: "Meka" },
  { word: "మైలు", transliteration: "Mailu" },
  { word: "మొగ్గ", transliteration: "Mogga" },
  { word: "మోటు", transliteration: "Motu" },
  { word: "మౌళి", transliteration: "Mauli" },
  { word: "మంట", transliteration: "Manta" },
  { word: "యతి", transliteration: "Yathi" },
  { word: "యాత్ర", transliteration: "Yaatra" },
  { word: "యుక్తి", transliteration: "Yukthi" },
  { word: "యోగి", transliteration: "Yogi" },
  { word: "రమ", transliteration: "Rama" },
  { word: "రాగి", transliteration: "Raagi" },
  { word: "రిమ్మ", transliteration: "Rimma" },
  { word: "శీలు", transliteration: "Sheelu" },
  { word: "రుచి", transliteration: "Ruchi" },
  { word: "రూక", transliteration: "Ruuka" },
  { word: "రెప్ప", transliteration: "Reppa" },
  { word: "రేకు", transliteration: "Reku" },
  { word: "రెలు", transliteration: "Relu" },
  { word: "రొట్టె", transliteration: "Rotte" },
  { word: "రోలు", transliteration: "Rolu" },
  { word: "రౌతు", transliteration: "Rauthu" },
  { word: "రంగు", transliteration: "Rangu" },
  { word: "లక్క", transliteration: "Lakka" },
  { word: "లావు", transliteration: "Laavu" },
  { word: "లిపి", transliteration: "Lipi" },
  { word: "లీల", transliteration: "Leela" },
  { word: "లుబ్ధు", transliteration: "Lubdhu" },
  { word: "లూటి", transliteration: "Luuti" },
  { word: "లెక్క", transliteration: "Lekka" },
  { word: "లేత", transliteration: "Letha" },
  { word: "లైను", transliteration: "Lainu" },
  { word: "లొట్ట", transliteration: "Lotta" },
  { word: "లోతు", transliteration: "Lothu" },
  { word: "టౌను", transliteration: "Townu" },
  { word: "లంగా", transliteration: "Langa" },
  { word: "వర", transliteration: "Vara" },
  { word: "వారు", transliteration: "Vaaru" },
  { word: "విడి", transliteration: "Vidi" },
  { word: "వీరు", transliteration: "Veeru" },
  { word: "వూట", transliteration: "Vuuta" },
  { word: "వృద్ది", transliteration: "Vruddhi" },
  { word: "వెండి", transliteration: "Vendi" },
  { word: "వేలు", transliteration: "Velu" },
  { word: "వైరి", transliteration: "Vairi" },
  { word: "వంక", transliteration: "Vanka" },
  { word: "శశి", transliteration: "Shashi" },
  { word: "శాల", transliteration: "Shaala" },
  { word: "శీల", transliteration: "Sheela" },
  { word: "శీను", transliteration: "Sheenu" },
  { word: "శుచి", transliteration: "Shuchi" },
  { word: "శూల", transliteration: "Shuula" },
  { word: "శృంగి", transliteration: "Shrungi" },
  { word: "శేష", transliteration: "Shesha" },
  { word: "శైలు", transliteration: "Shailu" },
  { word: "శోభ", transliteration: "Shobha" },
  { word: "శౌరి", transliteration: "Shauri" },
  { word: "శంక", transliteration: "Shanka" },
  { word: "షష్ఠి", transliteration: "Shashthi" },
  { word: "సత్య", transliteration: "Satya" },
  { word: "సాక్షి", transliteration: "Saakshi" },
  { word: "సిగ్గు", transliteration: "Siggu" },
  { word: "సీత", transliteration: "Seeta" },
  { word: "సుర", transliteration: "Sura" },
  { word: "సుడి", transliteration: "Sudi" },
  { word: "సూది", transliteration: "Suudi" },
  { word: "సెగ", transliteration: "Sega" },
  { word: "సేవ", transliteration: "Seva" },
  { word: "సైగ", transliteration: "Saiga" },
  { word: "సొమ్ము", transliteration: "Sommu" },
  { word: "సోది", transliteration: "Sodi" },
  { word: "సంత", transliteration: "Santha" },
  { word: "హస్తి", transliteration: "Hasthi" },
  { word: "హాయి", transliteration: "Haayi" },
  { word: "హంస", transliteration: "Hamsa" },
  { word: "హుండి", transliteration: "Hundi" },
  { word: "హెచ్చు", transliteration: "Hechu" },
  { word: "హేమ", transliteration: "Hema" },
  { word: "హైమ", transliteration: "Haima" },
  { word: "క్షయ", transliteration: "Kshaya" },
  { word: "క్షామం", transliteration: "Kshamam" },
  { word: "క్షితి", transliteration: "Kshiti" }
]

export const threeLetterWords: TeluguWord[] = [
  // To be populated with 3-letter words
]

export const fourLetterWords: TeluguWord[] = [
  // To be populated with 4-letter words
]

export const otherWords: TeluguWord[] = [
  // To be populated with words longer than 4 letters
]

// Helper function to get words by length category
export function getWordsByLength(category: "2" | "3" | "4" | "other"): TeluguWord[] {
  switch (category) {
    case "2":
      return twoLetterWords
    case "3":
      return threeLetterWords
    case "4":
      return fourLetterWords
    case "other":
      return otherWords
    default:
      return []
  }
}

// Helper function to get all words
export function getAllWordsByLength(): TeluguWord[] {
  return [...twoLetterWords, ...threeLetterWords, ...fourLetterWords, ...otherWords]
}

