// Maps the English gloss of a vocabulary word (shared identically across all
// six languages' lib/*-vocabulary-data.ts files) to a picture. Only words with
// an unambiguous, single-glyph emoji are included — Picture Vocabulary only
// draws from words that have an entry here, so categories like Days/Directions/
// Relatives (too abstract or too many near-duplicate pictures, e.g. every
// grandparent variant sharing the same emoji) are simply absent and skipped.

export const VOCABULARY_EMOJI: Record<string, string> = {
  // Fruits
  Mango: "🥭",
  Banana: "🍌",
  Apple: "🍎",
  Orange: "🍊",
  Grapes: "🍇",
  Pineapple: "🍍",
  Watermelon: "🍉",
  Muskmelon: "🍈",
  Coconut: "🥥",
  Lemon: "🍋",
  // Vegetables
  Potato: "🥔",
  Tomato: "🍅",
  Brinjal: "🍆",
  Carrot: "🥕",
  Cabbage: "🥬",
  Chili: "🌶️",
  Onion: "🧅",
  Peas: "🫛",
  Pumpkin: "🎃",
  // Birds
  Peacock: "🦚",
  Pigeon: "🕊️",
  Crow: "🐦‍⬛",
  Sparrow: "🐦",
  Parrot: "🦜",
  Eagle: "🦅",
  Hen: "🐔",
  Duck: "🦆",
  Swan: "🦢",
  Owl: "🦉",
  // Animals
  Cow: "🐄",
  Buffalo: "🐃",
  Goat: "🐐",
  Sheep: "🐑",
  Dog: "🐶",
  Cat: "🐱",
  Horse: "🐴",
  Donkey: "🫏",
  Elephant: "🐘",
  Lion: "🦁",
  Tiger: "🐯",
  Bear: "🐻",
  Fox: "🦊",
  Camel: "🐫",
  Rabbit: "🐰",
  Monkey: "🐵",
  // Colours
  Red: "🔴",
  Blue: "🔵",
  Green: "🟢",
  Yellow: "🟡",
  Black: "⚫",
  White: "⚪",
  Brown: "🟤",
  // Shapes
  Circle: "⭕",
  Square: "⬛",
  Triangle: "🔺",
  Star: "⭐",
  Heart: "❤️",
  // Body Parts
  Eye: "👁️",
  Ear: "👂",
  Nose: "👃",
  Mouth: "👄",
  Teeth: "🦷",
  Tongue: "👅",
  Hand: "✋",
  Leg: "🦵",
  Foot: "🦶",
  Finger: "👆",
  // Household Items
  Door: "🚪",
  Bed: "🛏️",
  Chair: "🪑",
  Cup: "☕",
  Plate: "🍽️",
  Broom: "🧹",
  Bucket: "🪣",
  // Seasons
  Spring: "🌸",
  Summer: "☀️",
  "Rainy Season": "🌧️",
  Autumn: "🍂",
  Winter: "❄️",
  // Professions
  Farmer: "🧑‍🌾",
  Doctor: "🧑‍⚕️",
  Teacher: "🧑‍🏫",
  Police: "👮",
  // Places
  School: "🏫",
  Shop: "🏪",
  City: "🏙️",
  Temple: "🛕",
  Road: "🛣️",
  River: "🏞️",
  Mountain: "⛰️",
  Forest: "🌲",
  House: "🏠",
}
